// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpR26XD-TSoG_CJN6m6xXaJpZB4XZ5E_Y',
    appId: '1:669650348877:web:45f25079b46bb5b8a0e504',
    messagingSenderId: '669650348877',
    projectId: 'greetings2024-cf16a',
    authDomain: 'greetings2024-cf16a.firebaseapp.com',
    storageBucket: 'greetings2024-cf16a.appspot.com',
    measurementId: 'G-6Q6PJ3FM3H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq-DAi0bprRNl8-7f3ALW1R6Ys0fA8KiY',
    appId: '1:669650348877:android:4369a0c6a723d458a0e504',
    messagingSenderId: '669650348877',
    projectId: 'greetings2024-cf16a',
    storageBucket: 'greetings2024-cf16a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1cZPJcOTCPOSMQKQZKIyCloDlCx-XjZc',
    appId: '1:669650348877:ios:71d0f897b1140931a0e504',
    messagingSenderId: '669650348877',
    projectId: 'greetings2024-cf16a',
    storageBucket: 'greetings2024-cf16a.appspot.com',
    iosBundleId: 'com.example.greetingsAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1cZPJcOTCPOSMQKQZKIyCloDlCx-XjZc',
    appId: '1:669650348877:ios:85d35b7a80384e34a0e504',
    messagingSenderId: '669650348877',
    projectId: 'greetings2024-cf16a',
    storageBucket: 'greetings2024-cf16a.appspot.com',
    iosBundleId: 'com.example.greetingsAdmin.RunnerTests',
  );
}
